version: '3.8'

services:
  python-server:
    build:
      context: .
      dockerfile: ./python-server/Dockerfile
    container_name: python-server
    networks:
      - wordcloud-network
    ports:
      - "50051:50051"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50051"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  java-client:
    build:
      context: .
      dockerfile: ./java-client/Dockerfile
    container_name: java-client
    networks:
      - wordcloud-network
    depends_on:
      python-server:
        condition: service_healthy

networks:
  wordcloud-network:
    driver: bridge
