# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wordcloud.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'wordcloud.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwordcloud.proto\" \n\x10WordCloudRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\"\n\x11WordCloudResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x32N\n\x10WordCloudService\x12:\n\x11GenerateWordCloud\x12\x11.WordCloudRequest\x1a\x12.WordCloudResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wordcloud_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORDCLOUDREQUEST']._serialized_start=19
  _globals['_WORDCLOUDREQUEST']._serialized_end=51
  _globals['_WORDCLOUDRESPONSE']._serialized_start=53
  _globals['_WORDCLOUDRESPONSE']._serialized_end=87
  _globals['_WORDCLOUDSERVICE']._serialized_start=89
  _globals['_WORDCLOUDSERVICE']._serialized_end=167
# @@protoc_insertion_point(module_scope)
